<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAP1238" name="com.demo.test.testcases.login.LoginPage_002_LoginFailFunction" tests="3" failures="2" timestamp="21 五月 2018 07:21:47 GMT" time="49.721" errors="0">
  <testcase name="loginPage_004_LoginWithWrongPwd" time="9.310" classname="com.demo.test.testcases.login.LoginPage_002_LoginFailFunction"/>
  <testcase name="loginPage_004_LoginWithWrongPwd" time="20.108" classname="com.demo.test.testcases.login.LoginPage_002_LoginFailFunction">
    <failure type="java.lang.AssertionError" message="超时!! 20 秒之后还没找到元素 [By.xpath: //*[@id=&#039;login_bt&#039;]/a[1]]">
      <![CDATA[java.lang.AssertionError: 超时!! 20 秒之后还没找到元素 [By.xpath: //*[@id='login_bt']/a[1]]at org.testng.Assert.fail(Assert.java:96)at com.demo.test.utils.SeleniumUtil.waitForElementToLoad(SeleniumUtil.java:206)at com.demo.test.pageshelper.HomePageHelper.waitHomeLoginButtonLoad(HomePageHelper.java:22)at com.demo.test.testcases.login.LoginPage_002_LoginFailFunction.loginPage_004_LoginWithWrongPwd(LoginPage_002_LoginFailFunction.java:15)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:606)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginPage_004_LoginWithWrongPwd -->
  <testcase name="loginPage_004_LoginWithWrongPwd" time="20.303" classname="com.demo.test.testcases.login.LoginPage_002_LoginFailFunction">
    <failure type="java.lang.AssertionError" message="超时!! 20 秒之后还没找到元素 [By.xpath: //*[@id=&#039;login_bt&#039;]/a[1]]">
      <![CDATA[java.lang.AssertionError: 超时!! 20 秒之后还没找到元素 [By.xpath: //*[@id='login_bt']/a[1]]at org.testng.Assert.fail(Assert.java:96)at com.demo.test.utils.SeleniumUtil.waitForElementToLoad(SeleniumUtil.java:206)at com.demo.test.pageshelper.HomePageHelper.waitHomeLoginButtonLoad(HomePageHelper.java:22)at com.demo.test.testcases.login.LoginPage_002_LoginFailFunction.loginPage_004_LoginWithWrongPwd(LoginPage_002_LoginFailFunction.java:15)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:606)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginPage_004_LoginWithWrongPwd -->
</testsuite> <!-- com.demo.test.testcases.login.LoginPage_002_LoginFailFunction -->
